name: Build - Linux

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      V8_VERSION: 15.1.206.16
      LLVM_VERSION: 23

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev pkg-config
          sudo apt-get install -y build-essential

      - name: Cache LLVM/Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: /usr/lib/llvm-${{ env.LLVM_VERSION }}
          key: llvm-clang-${{ env.LLVM_VERSION }}-linux64

      - name: Install LLVM/Clang
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ env.LLVM_VERSION }}

      - name: Setup LLVM/Clang
        run: |
          sudo ln -s /usr/lib/llvm-${{ env.LLVM_VERSION }}/lib/clang/${{ env.LLVM_VERSION }}/lib/linux \
                     /usr/lib/llvm-${{ env.LLVM_VERSION }}/lib/clang/${{ env.LLVM_VERSION }}/lib/x86_64-unknown-linux-gnu
          sudo ln -s /usr/lib/llvm-${{ env.LLVM_VERSION }}/lib/clang/${{ env.LLVM_VERSION }}/lib/linux/libclang_rt.builtins-x86_64.a \
                     /usr/lib/llvm-${{ env.LLVM_VERSION }}/lib/clang/${{ env.LLVM_VERSION }}/lib/linux/libclang_rt.builtins.a

          echo "/usr/lib/llvm-${{ env.LLVM_VERSION }}" >> $GITHUB_PATH

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Configure depot_tools
        run: |
          git config --global depot-tools.allowGlobalGitConfig true
          gclient

      - name: Fetch V8
        run: |
          fetch v8
          cd v8
          git checkout ${{ env.V8_VERSION }}
          gclient sync -D --no-history --reset

      - name: Patch V8
        run: |
          cd v8
          git apply --3way --ignore-whitespace ../linux/x64/patches/${{ env.V8_VERSION }}/v8.patch

      - name: Run GN
        run: |
          cd v8
          mkdir -p out/release
          cp ../linux/x64/args.gn out/release/args.gn
          gn gen out/release

      - name: Compile V8
        run: |
          cd v8
          ninja -C out/release v8_monolith

      - name: Stage Artifact
        run: |
          mkdir -p dist/lib
          mkdir -p dist/include
          
          cp v8/out/release/obj/libv8_monolith.a dist/lib/
          rsync -avm --include='*/' --include='*.h' --exclude='*' v8/include/ dist/include/
          cp v8/LICENSE* dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: v8-${{ env.V8_VERSION }}-linux64
          path: dist/